version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - new_volume:/var/lib/postgresql/data
    networks:
      - service-network

volumes:
  new_volume:

networks:
  service-network: